GET localhost:4000/api/courses?page=2&limit=1

###
GET localhost:4000/api/courses/68bc6c120897ba90ca5ed172

###

POST localhost:4000/api/courses
Content-Type: application/json

{
  "name": "jquery",
  "price": 300
}
###
PATCH localhost:4000/api/courses/68bdaa52acbbefab3b9ad314
Content-Type: application/json

{
  "price": 130
}
###

DELETE localhost:4000/api/courses/68bdaacdc94804a61629d790
